"""Ajout tuteur et date_enregistrement à Eleve

Revision ID: 5ef60b87000c
Revises: e5a22cf5881b
Create Date: 2025-09-06 23:44:21.573156

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5ef60b87000c'
down_revision = 'e5a22cf5881b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tuteur', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('telephone_tuteur', sa.String(length=15), nullable=True))
        batch_op.add_column(sa.Column('date_enregistrement', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_column('date_enregistrement')
        batch_op.drop_column('telephone_tuteur')
        batch_op.drop_column('tuteur')

    # ### end Alembic commands ###
