"""Ajout champ statut et cascade delete

Revision ID: 6c6e2ebde1c3
Revises: 5ef60b87000c
Create Date: 2025-10-05 22:47:46.219990

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c6e2ebde1c3'
down_revision = '5ef60b87000c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('statut', sa.String(length=20), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.drop_column('statut')

    # ### end Alembic commands ###
