"""add is_active date_inscription to ecole

Revision ID: 8060222b12c1
Revises: 
Create Date: 2026-04-25 04:05:57.957662

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8060222b12c1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_active', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('date_inscription', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.drop_column('date_inscription')
        batch_op.drop_column('is_active')

    # ### end Alembic commands ###
