"""migration supabase

Revision ID: e2888d1bcd57
Revises: f53a31e36b21
Create Date: 2026-03-07 08:11:57.384689

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e2888d1bcd57'
down_revision = 'f53a31e36b21'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('_alembic_tmp_eleve')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_alembic_tmp_eleve',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('prenom', sa.VARCHAR(length=50), nullable=False),
    sa.Column('nom', sa.VARCHAR(length=50), nullable=False),
    sa.Column('date_naissance', sa.DATE(), nullable=True),
    sa.Column('sexe', sa.VARCHAR(length=1), nullable=True),
    sa.Column('classe_id', sa.INTEGER(), nullable=False),
    sa.Column('tuteur', sa.VARCHAR(length=100), nullable=True),
    sa.Column('telephone_tuteur', sa.VARCHAR(length=15), nullable=True),
    sa.Column('date_enregistrement', sa.DATETIME(), nullable=True),
    sa.Column('matricule', sa.VARCHAR(length=20), nullable=False),
    sa.ForeignKeyConstraint(['classe_id'], ['classe.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
