"""Ajout champs professeur, horaire à Matiere

Revision ID: e5a22cf5881b
Revises: 
Create Date: 2025-09-06 23:08:52.259646

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e5a22cf5881b'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matiere', schema=None) as batch_op:
        batch_op.add_column(sa.Column('professeur', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('jour', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('heure', sa.Time(), nullable=True))
        batch_op.add_column(sa.Column('duree', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('matiere', schema=None) as batch_op:
        batch_op.drop_column('duree')
        batch_op.drop_column('heure')
        batch_op.drop_column('jour')
        batch_op.drop_column('professeur')

    # ### end Alembic commands ###
