"""add matricule to eleve

Revision ID: eed65ff679ad
Revises: f2f6b839019b
Create Date: 2026-03-04 23:22:26.086326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eed65ff679ad'
down_revision = 'f2f6b839019b'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.String(length=20), nullable=True))
        batch_op.create_unique_constraint('uq_eleve_matricule', ['matricule'])

    # Remplir les matricules existants (élèves déjà en base)
    op.execute("""
        UPDATE eleve SET matricule = 'CLS' || classe_id || '-' || UPPER(HEX(RANDOMBLOB(2)))
        WHERE matricule IS NULL
    """)

    # Rendre la colonne NOT NULL après le remplissage
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.alter_column('matricule', nullable=False)


def downgrade():
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_constraint('uq_eleve_matricule', type_='unique')
        batch_op.drop_column('matricule')


#####
"""

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.add_column(sa.Column('matricule', sa.String(length=20), nullable=False))
        batch_op.create_unique_constraint(None, ['matricule'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eleve', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('matricule')

    # ### end Alembic commands ###

"""