"""Ajout type_ecole

Revision ID: f2f6b839019b
Revises: 6c6e2ebde1c3
Create Date: 2025-10-09 03:05:19.380326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2f6b839019b'
down_revision = '6c6e2ebde1c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.add_column(sa.Column('type_ecole', sa.String(length=20), nullable=True))

    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('trimestre',
               existing_type=sa.VARCHAR(length=2),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('note', schema=None) as batch_op:
        batch_op.alter_column('trimestre',
               existing_type=sa.VARCHAR(length=2),
               nullable=True)

    with op.batch_alter_table('ecole', schema=None) as batch_op:
        batch_op.drop_column('type_ecole')

    # ### end Alembic commands ###
